### ISSUE TITLE
onPreCommit is deprecated

### ISSUE THREAD

**Issue by hiroshi-homma** [mvarnagiris/compose-glide-image#5]
The latest version is 1.0.0-alpha02 (jetpack compose)

In version, "onPreCommit" is deprecated.

I would be grateful if you could change the "onPreCommit" part to "onCommit".

https://github.com/mvarnagiris/compose-glide-image/blob/b129595f8819b612ce932fe5cc836689f0d34abc/compose-glide-image/src/main/java/com/koduok/compose/glideimage/GlideImage.kt#L36

**Comment by mvarnagiris** [comment]
Wanna do a PR? I would be happy to merge it. And it would be good to update it to alpha02. If not I will try to do it later today

**Comment by mvarnagiris** [comment]
https://github.com/mvarnagiris/compose-glide-image/releases/tag/0.3.9
